name: Greetings 😀

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
    - run: |
        mkdir content
        echo "hello 1" > content/file1.txt
    - name: Upload First
      uses: actions/upload-artifact@v2
      with:
        name: an-artifact
        path: content/file1.txt
        retention-days: 15
